#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output Virtual1 --mode 1920x1080
picom &
nitrogen --restore &
polybar &

bspc monitor -d           

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
